baseURL = 'auntjoestar.github.io/cs50NameChanger/'
languageCode = 'es-ni'
title = 'CS50 Name Changer'
theme = "hyde"
defaultContentLanguage = "es"
canonicalURL = "https://auntjoestar.github.io/cs50NameChanger/"
keywords = ["CS50", "Name Changer", "CS50 Name Changer", "CS50x", "Web50"]


[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true


[params]
  description = "Una aplicación de escritorio para cambiar el nombre de las fotos según el formato oficial de CS50"
  logo = "img/logo.png"
  icon = "icon/favicon.ico"
  copyright = "© 2024 - CS50 Name Changer"

[menu]

  [[menu.main]]
    name = "Acerca de"
    url = "/about/"
    weight = 2

  [[menu.main]]
    name = "Descargar"
    url = "/downloads/"
    weight = 3

  [[menu.main]]
    name = "Cómo usar"
    url = "/how-to-use/"
    weight = 4

