// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeFileNames(arg1, arg2) {
  return window['go']['main']['App']['ChangeFileNames'](arg1, arg2);
}

export function ConnectDB() {
  return window['go']['main']['App']['ConnectDB']();
}

export function CreateCycle(arg1, arg2) {
  return window['go']['main']['App']['CreateCycle'](arg1, arg2);
}

export function CreateDB() {
  return window['go']['main']['App']['CreateDB']();
}

export function CreateGroup(arg1, arg2) {
  return window['go']['main']['App']['CreateGroup'](arg1, arg2);
}

export function CreateProgram(arg1) {
  return window['go']['main']['App']['CreateProgram'](arg1);
}

export function CreateWeek(arg1, arg2) {
  return window['go']['main']['App']['CreateWeek'](arg1, arg2);
}

export function ListCycles(arg1) {
  return window['go']['main']['App']['ListCycles'](arg1);
}

export function ListGroups(arg1) {
  return window['go']['main']['App']['ListGroups'](arg1);
}

export function ListPrograms() {
  return window['go']['main']['App']['ListPrograms']();
}

export function ListWeeks(arg1) {
  return window['go']['main']['App']['ListWeeks'](arg1);
}

export function MakeNewName(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MakeNewName'](arg1, arg2, arg3, arg4);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}
