// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeFileNames(arg1, arg2) {
  return window['go']['main']['App']['ChangeFileNames'](arg1, arg2);
}

export function CloseDB() {
  return window['go']['main']['App']['CloseDB']();
}

export function ConnectDB() {
  return window['go']['main']['App']['ConnectDB']();
}

export function CreateCycle(arg1, arg2) {
  return window['go']['main']['App']['CreateCycle'](arg1, arg2);
}

export function CreateDB() {
  return window['go']['main']['App']['CreateDB']();
}

export function CreateGroup(arg1, arg2) {
  return window['go']['main']['App']['CreateGroup'](arg1, arg2);
}

export function CreateProgram(arg1) {
  return window['go']['main']['App']['CreateProgram'](arg1);
}

export function CreateWeek(arg1, arg2) {
  return window['go']['main']['App']['CreateWeek'](arg1, arg2);
}

export function DeleteCycle(arg1) {
  return window['go']['main']['App']['DeleteCycle'](arg1);
}

export function DeleteGroup(arg1) {
  return window['go']['main']['App']['DeleteGroup'](arg1);
}

export function DeleteProgram(arg1) {
  return window['go']['main']['App']['DeleteProgram'](arg1);
}

export function DeleteWeek(arg1) {
  return window['go']['main']['App']['DeleteWeek'](arg1);
}

export function EditCycle(arg1, arg2) {
  return window['go']['main']['App']['EditCycle'](arg1, arg2);
}

export function EditGroup(arg1, arg2) {
  return window['go']['main']['App']['EditGroup'](arg1, arg2);
}

export function EditProgram(arg1, arg2) {
  return window['go']['main']['App']['EditProgram'](arg1, arg2);
}

export function EditWeek(arg1, arg2) {
  return window['go']['main']['App']['EditWeek'](arg1, arg2);
}

export function ListCycles(arg1) {
  return window['go']['main']['App']['ListCycles'](arg1);
}

export function ListGroups(arg1, arg2) {
  return window['go']['main']['App']['ListGroups'](arg1, arg2);
}

export function ListPrograms() {
  return window['go']['main']['App']['ListPrograms']();
}

export function ListWeeks(arg1, arg2) {
  return window['go']['main']['App']['ListWeeks'](arg1, arg2);
}

export function MakeNewName(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MakeNewName'](arg1, arg2, arg3, arg4);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}

export function OpenFolder(arg1) {
  return window['go']['main']['App']['OpenFolder'](arg1);
}

export function WatchCycles() {
  return window['go']['main']['App']['WatchCycles']();
}

export function WatchGroups() {
  return window['go']['main']['App']['WatchGroups']();
}

export function WatchPrograms() {
  return window['go']['main']['App']['WatchPrograms']();
}

export function WatchWeeks() {
  return window['go']['main']['App']['WatchWeeks']();
}
