// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ChangeFileNames(arg1, arg2) {
  return window['go']['main']['App']['ChangeFileNames'](arg1, arg2);
}

export function ListCycles() {
  return window['go']['main']['App']['ListCycles']();
}

export function ListGroups() {
  return window['go']['main']['App']['ListGroups']();
}

export function ListPrograms() {
  return window['go']['main']['App']['ListPrograms']();
}

export function ListWeeks() {
  return window['go']['main']['App']['ListWeeks']();
}

export function MakeNewName(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['MakeNewName'](arg1, arg2, arg3, arg4);
}

export function OpenFileDialog() {
  return window['go']['main']['App']['OpenFileDialog']();
}
